# -*- coding: utf-8 -*-
"""TSA_Lab4_E20CSE470.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-Vi--5Lp-LyST0aSIa2ptZ_yN-XnpZwe
"""

pip install statsmodels

import pandas as pd
import numpy as np
from statsmodels.tsa.seasonal import seasonal_decompose

df=pd.read_csv("AirPassengers.csv")

df.head()

from statsmodels.tsa.stattools import kpss

import plotly.express as px

#df.set_index('Date',inplace=True)
df.Date=pd.to_datetime(df.Month)

series = df.loc[:, '#Passengers'].values
fig = px.line(df, x='Month', y='#Passengers')
fig.show()

kpsstest= kpss(series, regression='c')

kpss_output=pd.Series(kpsstest[0:3], index=['Test Statistical','p-value','Lags Used'])
for key,value in kpsstest[3].items():
  kpss_output['Critical Value (%s)' %key]=value
print(kpss_output)

df['rolling_mean'] = df['#Passengers'].rolling(window=12).mean()
df['rolling_std'] = df['#Passengers'].rolling(window=12).std()

df['rolling_mean']

df['rolling_std']

result=seasonal_decompose(df['#Passengers'],model='multiplicable',period=12)
result.seasonal.plot()
result.trend.plot()
result.plot()

